# Generated by Django 5.2.8 on 2025-11-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='curp',
        ),
    ]
