# Generated by Django 6.0 on 2025-12-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='xml',
        ),
    ]
