# Generated by Django 5.2.8 on 2025-11-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(help_text='Selecciona cualquier día del mes que quieres analizar')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_pacientes', models.PositiveIntegerField(default=0, editable=False)),
                ('pacientes_nuevos_mes', models.PositiveIntegerField(default=0, editable=False)),
                ('tratamientos_iniciados', models.PositiveIntegerField(default=0, editable=False)),
                ('tratamientos_completados', models.PositiveIntegerField(default=0, editable=False)),
                ('productos_bajo_stock', models.PositiveIntegerField(default=0, editable=False)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Reporte Mensual',
                'verbose_name_plural': 'Reportes Mensuales',
            },
        ),
    ]
