# Generated by Django 5.2.8 on 2025-11-22 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_remove_paciente_curp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('sala', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('odontologo', models.ForeignKey(help_text='Usuario con rol de odontólogo', on_delete=django.db.models.deletion.PROTECT, related_name='citas_odontologo', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('odontologo', 'fecha', 'hora_inicio')},
            },
        ),
    ]
